apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapi
  labels:
    app: goapi
spec:
  replicas: 4
  selector:
    matchLabels:
      app: goapi
  template:
    metadata:
      labels:
        app: goapi
    spec:
      containers:
        - name: goapi
          envFrom:
            - configMapRef:
                name: goconfigmap
          image: edwinwalela/k8-go-api
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: goapi
spec:
  type: LoadBalancer
  selector:
    app: goapi
  ports:
  - port: 8000 # Service port
    targetPort: 3000 # pod port
    nodePort: 30020
