apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: client-b
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          envFrom:
            - configMapRef:
                name: mysqlconfigmap
          image: mysql
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 3306
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - port: 3306 # Service port
    targetPort: 3306 # pod port
