apiVersion: v1
kind: ConfigMap
metadata:
  name: blogconfigmap
data:
  APP_DEBUG: "false"
  APP_ENV: production
  APP_KEY: changeme
  APP_LOG_LEVEL: debug
  APP_NAME: "laravel"
  APP_URL: 0.0.0.0:8000
  BROADCAST_DRIVER: pusher
  CACHE_DRIVER: redis
  QUEUE_DRIVER: redis
  SESSION_DRIVER: redis
  DB_CONNECTION: mysql
  DB_DATABASE: task
  DB_HOST: host
  DB_PASSWORD: password
  DB_PORT: "3306"
  DB_USERNAME: username
  REDIS_HOST: redis
  REDIS_PORT: "6379"
