apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: client-b
  labels:
    app: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          envFrom:
            - configMapRef:
                name: blogconfigmap
          image: edwinwalela/k8-blog
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  type: LoadBalancer
  selector:
    app: blog
  ports:
  - port: 8000 # Service port
    targetPort: 8000 # pod port
    nodePort: 30000
